name: "Pratik's Blogs"
description: "Programming essays, thoughts, and notes."
baseurl: "/Blogs" # The repository name is Blogs
url: ""

collections:
  blogs:
    output: true
    permalink: /blogs/:name/
